### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPoV2#1]
Start from blank Chrome extension or fork [AddArt](https://github.com/coreytegeler/add-art-chrome) to create a version that simply replaces ads with colored squares.

**Comment by cqx931** [comment]
https://github.com/dhowe/AdLiPo/commit/a568eaf0be49140ea2f9a2e25fc6dfdede37757b
A simple implementation for most of the iframes & img. Some issues need to be fixed for it to work on Div for Text-ads

**Comment by cqx931** [comment]
I have added the files from web folder for temporary testing. 
If you uncomment this line, there shall be texts generated in the wrapper.
https://github.com/dhowe/AdLiPo/blob/master/js/artAdder.js#L113
Though currently the padding changes from AdLiPo will interfere with the layout, so I have commented it out for now.

**Comment by dhowe** [comment]
👍

**Comment by cqx931** [comment]
fninshed
