### ISSUE TITLE
Missing lists directory (+ other errors)

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPoV2#21]
![screen shot 2017-01-14 at 11 45 55 am](https://cloud.githubusercontent.com/assets/737638/21952124/43453e04-da4f-11e6-8e68-2f5aacbfffcd.png)

**Comment by cqx931** [comment]
Please check the latest update: https://github.com/dhowe/AdLiPo/pull/22

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/AdLiPo/commit/f3c4fe3c6418631c7db5821b17057366b35ec10a
