### ISSUE TITLE
No hover/anchor for generated ads

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPoV2#28]
should show 'AdLiPo-generated Ad' on hover and lead to the webpage on click...

**Comment by cqx931** [comment]
Is this a new feature that I should add?

**Comment by dhowe** [comment]
this was in version 1

**Comment by cqx931** [comment]
add this here https://github.com/dhowe/AdLiPo/commit/d7b2a5876f14484ecca587d9e0c05642a8b20a62
