### ISSUE TITLE
Text Layout issue

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdLiPoV2#3]
Text go out of the boundary
<img width="983" alt="screen shot 2016-10-21 at 5 04 01 pm" src="https://cloud.githubusercontent.com/assets/3056154/19592943/b73f4dfe-97b0-11e6-8632-a0fbae8a5a05.png">
<img width="804" alt="screen shot 2016-10-21 at 4 59 42 pm" src="https://cloud.githubusercontent.com/assets/3056154/19592946/c146cc28-97b0-11e6-8e9b-4c07712b3dbc.png">

**Comment by dhowe** [comment]
I also see that the correct font is not being used...

**Comment by cqx931** [comment]
This shall be fixed by https://github.com/dhowe/AdLiPo/pull/6/commits/bc446b61560c586548df0e10cdba72ba4abe7230

<img width="1044" alt="screen shot 2016-10-24 at 2 05 28 pm" src="https://cloud.githubusercontent.com/assets/3056154/19635177/10dd38b4-99f3-11e6-8edf-d393aef988e5.png">
