### ISSUE TITLE
Font sizing incorrect for available ad space ?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPoV2#31]
Not sure how to test this correctly, but it seems as if the space available is not be calculated correctly, so that a smaller font size is selected, and the text then does not fill the vertical space. I've seen a number of ads laid out like those below where there is lots of space at the bottom, and it appears that a larger font size could have been used:

page: http://edition.cnn.com/

![screen shot 2017-01-14 at 4 56 29 pm](https://cloud.githubusercontent.com/assets/737638/21953757/a83abbba-da7a-11e6-95c7-173fa7c83c29.png)

![screen shot 2017-01-14 at 5 01 37 pm](https://cloud.githubusercontent.com/assets/737638/21953784/26ac3f78-da7b-11e6-9ae1-6c7f173c9fb0.png)

![screen shot 2017-01-14 at 5 03 30 pm](https://cloud.githubusercontent.com/assets/737638/21953799/7046e16a-da7b-11e6-9581-f5ab7b181361.png)

**Comment by cqx931** [comment]
just verified that this is a bug caused by calculating the span width before the font is loaded. So that the width calculated was not for the current font, but a default one.

**Comment by cqx931** [comment]
Reference: https://medium.com/@matuzo/getting-started-with-css-font-loading-e24e7ffaa791#.y4govstsf

**Comment by dhowe** [comment]
is this fixed in the above PR?

**Comment by cqx931** [comment]
yes
