### ISSUE TITLE
Mixed fonts?

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPoV2#35]
I've seen this a few times... but can't imagine how or why it is happening

![screen shot 2017-01-16 at 1 21 58 pm](https://cloud.githubusercontent.com/assets/737638/21971783/dd388de0-dbee-11e6-8d56-33520d711526.png)

**Comment by cqx931** [comment]
I have never seen this... can you post an example page?

**Comment by dhowe** [comment]
![screen shot 2017-01-16 at 3 29 30 pm](https://cloud.githubusercontent.com/assets/737638/21974266/b48c6eae-dc00-11e6-89c5-56dd51bfc430.png)

**Comment by cqx931** [comment]
This should fix the cnn case.
https://github.com/dhowe/AdLiPo/pull/36

**Comment by cqx931** [comment]
Should have been solved with the latest font loading. Close for now.
