### ISSUE TITLE
Commit 4c7d5dfc4a86 breaks website

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdLiPoV2#40]
Not sure how this wasn't noticed til now, but commit 4c7d5dfc4a86 seems to totally break the website.

Please check ASAP

**Comment by cqx931** [comment]
fixed

**Comment by dhowe** [comment]
is this fix live? did we temp. remove the link below?

**Comment by dhowe** [comment]
![Screen Shot 2019-06-26 at 2 25 33 PM](https://user-images.githubusercontent.com/737638/60206007-a4a28300-9820-11e9-9bae-4973c56ae429.png)

**Comment by cqx931** [comment]
yes, the adlipo website was fixed in Feb, the links were gone from a bug introduced in a latest commit in the website, should be fixed [here](https://github.com/dhowe/Website/commit/024bc4e698bfc37291359e8bf9a4f2eb48cea2ac)
