### ISSUE TITLE
Logo in color

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdLiPoV2#9]
Can you find the logo in vector image? It's better if I change the color in vector file.

This is logo with two colors from the color scheme.#CF8D2F  #C55532
Personally I find the logo should be a bit more brighter but it also looks ok with the current color scheme.

![screen shot 2016-11-28 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/3056154/20657319/fbc1ccfe-b56f-11e6-8988-fa3a12097f01.png)

**Comment by cqx931** [comment]
on the left is a version with brighter orange color
on the right is one with two colors from the color palette.#CF8D2F #C55532
![image](https://cloud.githubusercontent.com/assets/3056154/20874698/48d85812-baef-11e6-8200-23d92b0954a0.png)

**Comment by dhowe** [comment]
maybe a combination (with the brighter orange from the left, and the red from the right?)

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/20885839/fbceeb3c-bb2d-11e6-893e-99bfdd017458.png)

**Comment by dhowe** [comment]
looks good for now, thanks
